import sys
import os
import csv
import re
from pathlib import Path
from typing import List, Set, Dict

try:
    from forti4d.lib.reader_logical import read_logical_lines
    from forti4d.lib.patterns_v1 import (
        RE_PROGRAM,
        RE_MODULE,
        RE_SUBROUTINE,
        RE_FUNCTION,
        RE_BLOCK_DATA,
        RE_END_GENERIC,
        RE_INTERFACE,
    )
except ImportError as e:
    print(f"ERROR: {e}")
    sys.exit(1)

# =============================================================================
# CONFIGURATION
# =============================================================================
from forti4d.config import CODE_PATH, RESULTS_PATH

OUTPUT_FILE = RESULTS_PATH / "inventory_report.csv"

# --- AUDIT LISTS (Report) ---
LEGACY_LIST = ["COMMON", "EQUIVALENCE", "PAUSE", "ENTRY", "ASSIGN", "GO TO", "COMPUTED GOTO", "ARITHMETIC IF"]
IO_LIST = ["READ", "WRITE", "PRINT", "OPEN", "CLOSE", "INQUIRE", "BACKSPACE", "REWIND", "NAMELIST"]
CUSTOM_LIST = ["ALLOCATE", "DEALLOCATE", "DATA", "STOP"]

# --- IMPLICIT MAIN TRIGGER LIST (Fortran Hierarchy) ---
# Based on the "Hierarchy and Statement Order" document.
# If we find this and no unit is open, it IS an implicit main program.
TRIGGERS_SPECIFICATION = [
    "USE",
    "IMPORT",
    "IMPLICIT",
    "INTEGER",
    "REAL",
    "DOUBLE PRECISION",
    "COMPLEX",
    "LOGICAL",
    "CHARACTER",
    "BYTE",
    "TYPE",
    "CLASS",
    "PROCEDURE",
    "DIMENSION",
    "PARAMETER",
    "EXTERNAL",
    "INTRINSIC",
    "SAVE",
    "TARGET",
    "POINTER",
    "PUBLIC",
    "PRIVATE",
    "OPTIONAL",
    "INTENT",
    "VOLATILE",
    "ASYNCHRONOUS",
    "PROTECTED",
    "DATA",
    "FORMAT",
    "ENTRY",
    "NAMELIST",
    "COMMON",
    "EQUIVALENCE",
]
# Executable statements also trigger (IF, DO, CALL, etc.), but those
# are captured by flags or discarded. These are the critical declarative ones.


def compile_list(words):
    if not words:
        return None
    pattern = r"\b(" + "|".join(re.escape(p) for p in words) + r")\b"
    return re.compile(pattern, re.IGNORECASE)


RE_LEGACY = compile_list(LEGACY_LIST)
RE_IO = compile_list(IO_LIST)
RE_CUSTOM = compile_list(CUSTOM_LIST)

# Master Pattern for Implicit Start
RE_IMPLICIT_START = compile_list(TRIGGERS_SPECIFICATION)

# If patterns.py does not have RE_END_INTERFACE, the ideal is to add it there.
# But for the purposes of this script, we define a robust one that accepts optional names:
# This regex matches: "END", spaces, "INTERFACE", and optionally more things (name)
RE_END_INTERFACE = re.compile(r"^\s*END\s*INTERFACE\b", re.IGNORECASE)


class DetectedUnit:

    def __init__(self, utype: str, name: str, start_line: int, parent: str = "GLOBAL"):
        self.type = utype
        self.name = name
        self.start_line = start_line
        self.parent = parent
        self.end_line = -1
        self.flags_legacy: Set[str] = set()
        self.flags_io: Set[str] = set()
        self.flags_custom: Set[str] = set()

    @property
    def total_lines(self):
        if self.end_line == -1:
            return "?"
        return self.end_line - self.start_line + 1


def mask_strings(text: str) -> str:
    text = re.sub(r"'[^']*'", "''", text)
    text = re.sub(r'"[^"]*"', '""', text)
    return text


# Add this in src/inventory.py


def load_inventory(csv_path=None):
    """
    Reads the CSV report generated by this script and returns the complete
    data structure (SSOT) needed for other analyses.

    Returns:
        list[dict]: List of dicts with original keys
                    ('File', 'Type', 'Name', 'Start_Line', etc.)
    """
    import csv
    from pathlib import Path

    if csv_path is None:
        csv_path = RESULTS_PATH / "inventory_report.csv"

    csv_path = Path(csv_path)
    retrieved_data = []

    if not csv_path.exists():
        print(f"Warning: Inventory file not found: {csv_path}")
        return []

    try:
        with csv_path.open(mode="r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                # Critical type conversion for the profiler
                try:
                    # Use the EXACT keys defined when generating the CSV
                    row["Start_Line"] = int(row["Start_Line"])
                    row["End_Line"] = int(row["End_Line"])
                    row["Total_Lines"] = int(row["Total_Lines"])
                except (ValueError, KeyError) as e:
                    # If it fails, keep 0 to avoid breaking execution
                    row["Start_Line"] = 0
                    row["End_Line"] = 0
                    row["Total_Lines"] = 0

                retrieved_data.append(row)

    except Exception as e:
        print(f"Critical error reading inventory: {e}")
        return []

    return retrieved_data


def audit_file(file_path: Path, source_path: Path) -> List[Dict]:
    rel_path = str(file_path.relative_to(source_path))
    try:
        logical_lines = read_logical_lines(str(file_path))
    except Exception as e:
        return [{"File": file_path.name, "Relative_Path": rel_path, "Type": "ERROR", "Name": str(e)}]

    if not logical_lines:
        return []

    units = []
    stack = []

    # Control to avoid creating multiple Implicit Main units if there is scattered code
    implicit_main_active = False
    # Control to avoid creating definition units that are inside an INTERFACE block
    within_interface = False
    active_interface = None  # active INTERFACE/GENERIC_INTERFACE unit

    for lline in logical_lines:
        if lline.is_comment:
            continue

        text_raw = lline.text.strip()
        text_safe = mask_strings(text_raw)  # To search keywords without false positives
        line_num = lline.start_line

        # INTERFACE LOGIC considering when a generic interface is defined (contains MODULE PROCEDURE)

        # 0.1. State Check: Are we entering or leaving an INTERFACE?
        m_interface = RE_INTERFACE.match(text_safe)
        if m_interface:
            interface_name = m_interface.group(1)
            parent_name = stack[-1].name if stack else "GLOBAL"

            if interface_name:
                # Generic/named interface
                iface_type = "GENERIC_INTERFACE"
            else:
                # Anonymous interface: explicit declaration of external routines
                iface_type = "INTERFACE"
                interface_name = f"INTERFACE_{line_num}"

            new_interface = DetectedUnit(iface_type, interface_name, line_num, parent_name)
            active_interface = new_interface
            units.append(new_interface)

            within_interface = True
            continue  # Skip this line

        if RE_END_INTERFACE.match(text_safe):
            within_interface = False
            if active_interface is not None:
                active_interface.end_line = line_num
                active_interface = None
            continue  # Skip this line and resume normal detection

        # 0.2. If we are inside an interface, IGNORE everything
        #    because these are only prototypes, not real code.
        if within_interface:
            continue

        # END INTERFACE LOGIC

        # 1. DETECTION OF EXPLICIT OPENINGS
        # These take maximum priority over Implicit Main.
        m_prog = RE_PROGRAM.match(text_safe)
        m_mod = RE_MODULE.match(text_safe)
        m_sub = RE_SUBROUTINE.match(text_safe)
        m_func = RE_FUNCTION.match(text_safe)
        m_bd = RE_BLOCK_DATA.match(text_safe)

        # DETERMINE THE CURRENT PARENT
        # If the stack has elements, the top is our parent (e.g., Module)
        parent_name = stack[-1].name if stack else "GLOBAL"

        new_unit = None
        if m_prog:
            new_unit = DetectedUnit("PROGRAM", m_prog.group(1), line_num, parent_name)
        elif m_mod:
            new_unit = DetectedUnit("MODULE", m_mod.group(1), line_num, parent_name)
        elif m_sub:
            new_unit = DetectedUnit("SUBROUTINE", m_sub.group(1), line_num, parent_name)
        elif m_func:
            new_unit = DetectedUnit("FUNCTION", m_func.group(1), line_num, parent_name)
        elif m_bd:
            new_unit = DetectedUnit("BLOCK DATA", m_bd.group(1) or "data", line_num, parent_name)

        if new_unit:
            stack.append(new_unit)
            units.append(new_unit)
            # When we enter an explicit unit, we "pause" the notion of being at the implicit level
            # until this unit is closed.
            continue

        # Remember that Implicit Main would also have parent "GLOBAL" by default.

        # 2. DETECTION OF CLOSINGS (END)
        match_end = RE_END_GENERIC.match(text_safe)
        if match_end:
            kw = match_end.group(1) or ""
            if stack:
                top = stack[-1]
                # Logic: An END closes whatever is on top.
                # If the top is IMPLICIT-MAIN, it is only closed if we find a bare END
                # (or END PROGRAM if we were lenient, but bare END is standard).

                # Type match (Subroutine with End Subroutine) OR generic End
                match_type = (kw.upper() in top.type) if kw else True

                if match_type:
                    closed_unit = stack.pop()
                    closed_unit.end_line = line_num

                    if closed_unit.type == "IMPLICIT-MAIN":
                        implicit_main_active = False  # Main is closed, no more code expected
                    continue

        # 3. IMPLICIT MAIN ACTIVATION LOGIC (Hierarchy)
        # If the stack is empty, we are "in the open".
        # Any valid statement here MUST trigger the Implicit Main.

        if not stack:
            # Is it an empty or irrelevant line? (comments already filtered)
            if not text_safe:
                continue

            # Look for Specification or Execution Triggers
            is_spec_trigger = RE_IMPLICIT_START.search(text_safe)

            # Also consider IO/Legacy flags as triggers (executable statements)
            is_exec_trigger = False
            if RE_IO and RE_IO.search(text_safe):
                is_exec_trigger = True
            if RE_LEGACY and RE_LEGACY.search(text_safe):
                is_exec_trigger = True
            if RE_CUSTOM and RE_CUSTOM.search(text_safe):
                is_exec_trigger = True

            # "Catch-all" trigger for assignments (x = 1) or Calls
            # If it has a '=' or starts with 'call', it is almost certainly executable.
            is_assign = ("=" in text_safe) or (text_safe.lower().startswith("call"))

            if is_spec_trigger or is_exec_trigger or is_assign:
                if not implicit_main_active:
                    # IMPLICIT-MAIN is born
                    implicit_main = DetectedUnit("IMPLICIT-MAIN", file_path.stem, line_num)
                    # Insert it chronologically. If it's the first, place it at the start.
                    units.append(implicit_main)
                    stack.append(implicit_main)
                    implicit_main_active = True
                else:
                    # Rare case: we had closed an Implicit Main and more loose code appears.
                    # Fortran does not allow two Main Programs. We assume it is a continuation or error;
                    # we reopen the last one or create a new one. For simplicity, we create a new one
                    # to avoid mixing.
                    pass

        # 4. FLAG CAPTURE (Content)
        if stack:
            current = stack[-1]

            # Legacy Flags
            if RE_LEGACY:
                for m in RE_LEGACY.findall(text_safe):
                    current.flags_legacy.add(m.upper())
            # IO Flags
            if RE_IO:
                for m in RE_IO.findall(text_safe):
                    current.flags_io.add(m.upper())
            # Custom Flags
            if RE_CUSTOM:
                for m in RE_CUSTOM.findall(text_safe):
                    current.flags_custom.add(m.upper())

    # Final safety close
    last_line = logical_lines[-1].start_line if logical_lines else 0
    for u in stack:
        if u.end_line == -1:
            u.end_line = last_line

    # GENERATE ROWS
    rows = []
    for u in units:
        # Noise filter for empty Implicit Mains (if created by mistake without real content)
        if u.type == "IMPLICIT-MAIN":
            has_content = u.flags_legacy or u.flags_io or u.flags_custom
            # We only filter if NO valid code lines were detected inside.
            # With the new logic, it is only created if there is a trigger.
            # Still, keep the filter if the user wants to ignore mains without 'audit'
            pass

        rows.append(
            {
                "File": file_path.name,
                "Relative_Path": rel_path,
                "Type": u.type,
                "Name": u.name,
                "Parent": u.parent,
                "Start_Line": u.start_line,
                "End_Line": u.end_line,
                "Total_Lines": u.total_lines,
                "Legacy": ", ".join(sorted(u.flags_legacy)),
                "IO": ", ".join(sorted(u.flags_io)),
                "Custom": ", ".join(sorted(u.flags_custom)),
            }
        )
    return rows


def main():
    source_path = CODE_PATH
    if not source_path.exists():
        print(f"Error: '{CODE_PATH}' does not exist")
        return

    files = sorted([f for f in source_path.rglob("*") if f.suffix.lower() in (".f90", ".f", ".for", ".f95")])
    print(f"--- Inventory V4 (Fortran Hierarchy) ---")

    data = []
    for file in files:
        data.extend(audit_file(file, source_path))

    if data:
        fields = [
            "File",
            "Relative_Path",
            "Type",
            "Name",
            "Parent",
            "Start_Line",
            "End_Line",
            "Total_Lines",
            "Legacy",
            "IO",
            "Custom",
        ]
        OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(OUTPUT_FILE, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fields)
            writer.writeheader()
            writer.writerows(data)
        print(f"Report generated: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
