MODULE ALPHA_MOD
  IMPLICIT NONE
CONTAINS
  SUBROUTINE ALPHA_INIT(x)
    REAL, INTENT(IN) :: x
  END SUBROUTINE ALPHA_INIT

  FUNCTION ALPHA_COMPUTE(x) RESULT(y)
    REAL, INTENT(IN) :: x
    REAL :: y
    y = x * 2.0
  END FUNCTION ALPHA_COMPUTE
END MODULE ALPHA_MOD
